# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: docs
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments.rb

# SEO settings
title: beatoraja
description: "beatoraja is a Cross-platform rhythm game."
keywords: "beatoraja, bms"

# Site settings
url: https://github.com/exch-bms2/beatoraja
baseurl: ""

# Author settings
author:
  name      : 
  job       : 
  bio       : 
  thumb     : /images/author.jpg
  email     : 
  url       : https://github.com/exch-bms2/beatoraja
  github    : https://github.com/exch-bms2/beatoraja

# google_analytics: 
repo: https://github.com/exch-bms2/beatoraja

# comments
# disqus_shortname: ""
